blank_issues_enabled: false
contact_links:
  - name: Discussion / General Questions
    url: https://forum.unity.com/forums/ml-agents.453/
    about: Discussion about ML-Agents, RL algorithms, or game integrations.
  - name: Installation / Setup
    url: https://forum.unity.com/forums/ml-agents.453/
    about: Questions about python installation, initial connection between Unity and training, etc.
  - name: ML-Agents Unity Forum
    url: https://forum.unity.com/forums/ml-agents.453/
    about: Please ask other questions in the ML-Agents Unity Forum.
